server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: StudentManagementSys
  datasource:
    url: jdbc:postgresql://localhost:5432/StudentMgSys
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

